services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:latest
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LS_AUTH_TOKEN:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  temporal:
    image: temporalio/temporal:latest
    container_name: temporal
    ports:
      - 7233:7233
      - 8233:8233
    command: server start-dev --ip 0.0.0.0

volumes:
  temporal-data: